name: nota
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  path_provider: ^2.1.5
  go_router: ^14.6.2
  analyzer: 5.13.0
  google_fonts: ^6.2.1
  popup_menu: ^2.1.0
  popover: ^0.3.1
  shared_preferences: ^2.3.4
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/appIcon.png"
  remove_alpha_ios: true
  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - assets/languages/en-US.json
    - assets/languages/ar-EG.json
    - assets/images/
    - assets/icons/